name = sbo_mobs
description = Adds a mob api for mods to add animals or monsters etc.
optional_depends = sbo_invisibility
depends = player_api, sbo_hbar, unified_inventory, sbo_core
min_minetest_version = 5.0
author = TenPlus1
title = Mob API
