name = sbo_plant_mechs
depends = sbo_core, sbz_resources, sbz_progression, sbo_photon, sbz_power, sbo_circuits, sbo_extrosim, sbo_resium
description = Adds Plant Machines
min_minetest_version = 5.0
title = Plant Machines
