name = sbo_laptop_rnd_app
description = Research N' Duplicate: Obtain and research enough of a specific item to unlock the ability to infinitely duplicate it. In other words, it's an "earned" creative mode.
min_minetest_version = 5.2.0
author = Noodlemire
title = Research N' Duplicate Laptop App
depends = sbo_computer
