name = sbo_long_teleporter
author = Wuzzy
description = Adds a magical item which teleports the user to a previously set location.
title = Long Range Teleporter
depends = sbo_core, sbz_progression, sbo_batterys

