name=sbo_crystals
title=Amethyst
depends=sbo_geodes, sbo_core, sbo_dark_glass, sbz_chem
optional_depends= mesecons_mvps
author = alerikaisattera
description = Amethyst, basalt, calcite and related building blocks
